- src/middleware/ensure-authenticated.ts
- src/middleware/translations/en.json
- src/routes/publish.ts
- src/routes/view.ts
- src/services/stats-wales-api.ts
- src/utils/latest.ts
- src/utils/single-lang-dataset.ts
- src/views/errors/not-found.ejs
- src/views/publish/tasklist.ejs
- test/helpers/mock-server.ts
- test/publish.test.ts
This adds a stub tasklist page for the create journey with placeholder links.
> SW-88: Add initial version of the tasklist page

- src/app.ts
- src/routes/dataset.ts
- src/routes/healthcheck.ts
- src/routes/publish.ts
There were a number of routes that do their own error handling so we need to check for 401 and then hand it off to the default error handler for the logout.
> Pass 401 exceptions through to the default error handler

- package.json
- src/@types/express/index.d.ts
- src/app.ts
- src/interfaces/authed-request.ts
- src/interfaces/authenticated-request.ts
- src/interfaces/service-container.ts
- src/middleware/ensure-authenticated.ts
- src/middleware/language-switcher.ts
- src/middleware/services.ts
- src/routes/auth.ts
- src/routes/dataset.ts
- src/routes/publish.ts
Currently if we want to use the StatsWalesApi anywhere we have to create a new instance of it in each router, as it needs the request object for the current language and the jwt token.
There's a pattern in Express where services (e.g. i18next, session, etc) get added to the request object so that they're available for the lifetime of the request.
I've basically done that with the StatsWalesApi which is now available via `req.swapi` and a locale based URL builder `req.buildUrl`.
I've also extended the standard request object with `req.user` and `req.jwt` so that we don't have to type the request object as `AuthedRequest` any more.
> Add services to request via middleware

- src/interfaces/service-container.ts
- src/middleware/ensure-authenticated.ts
- src/middleware/language-switcher.ts
- src/middleware/translations/en.json
- src/routes/auth.ts
- src/routes/error-handler.ts
- src/routes/publish.ts
- src/views/index.ejs
- src/views/publish/preview.ejs
- src/views/publish/sources.ejs
- src/views/publish/start.ejs
- src/views/publish/tasklist.ejs
- src/views/publish/title.ejs
- src/views/publish/upload.ejs
- test/publish.test.ts
This simplifies creating URLs by not having to worry about translation - just pass the builder the actual route and the expected locale, and it will return a URL string with the locale and a translated path.
If the current locale is English, it will just skip the path translation completely to save on the translation lookups.
> Use url builder to generate all URLs

- src/views/publish/sources.ejs
This adds the same placeholder text for missing column headers on the sources page (previously only the preview was showing it).
> Use unnamed col fallback on sources as well

- src/controllers/publish.ts
- src/dtos/dataset-info.ts
- src/middleware/translations/en.json
- src/routes/publish.ts
- src/validators/index.ts
- src/views/publish/quality.ejs
Adds a form for collecting statistical quality metadata.
> SW-130: Metadata - Statistical Quality

- src/controllers/publish.ts
- src/i18n/en.json
- src/views/publish/dimension-chooser.ejs
- src/views/publish/dimension-match-failure.ejs
- src/views/publish/upload.ejs
Fixes some minor issues with the lookup table journey
> Fixes some minor issues with the lookup table journey

- src/@types/express/index.d.ts
- src/app.ts
- src/exceptions/forbidden.exception.ts
- src/i18n/en.json
- src/interfaces/authenticated-request.ts
- src/interfaces/service-container.ts
- src/interfaces/user.interface.ts
- src/middleware/ensure-authenticated.ts
- src/middleware/ensure-developer.ts
- src/middleware/services.ts
- src/routes/developer.ts
- src/routes/error-handler.ts
- src/views/developer/data.ejs
- src/views/developer/list.ejs
- src/views/errors/forbidden.ejs
- src/views/errors/not-found.ejs
- src/views/homepage.ejs
- src/views/partials/header.ejs
- tests/error-handler.test.ts
Moved the dev pages (dataset list and dataset details) under `/developer` and limited access to those with a Marvell email until we have user roles.
> Moved dataset routes to /developer

- src/controllers/publish.ts
- src/views/publish/preview.ejs
The previous upload was being deleted before a new one was uploaded, meaning the user could be left in a state of having no uploaded fact table.
This PR moves the removal of the old fact table to happen once we upload a new one.
> FIX: SW-366 - move cleanup of old fact table to upload

- src/i18n/en.json
As per design review, support link text updated.
Consumer side:
> You’re viewing a new version of StatsWales
Publisher side:
> You’re viewing a new version of StatsWales. Get support at {{support_email}}.
> Fix: Updated beta banner content

- src/views/partials/header.ejs
Fixes a few issues with the frontend nav:
* "Publish dataset" link removed as it's not in the prototype
* "List datasets" was moved to "Developer" temp link that only shows for users authed with Marvell emails
* Guidance link should only display once authed
> Replace nav links in header

- src/views/publish/collection.ejs
- src/views/publish/designation.ejs
- src/views/publish/providers.ejs
- src/views/publish/quality.ejs
- src/views/publish/related-links.ejs
- src/views/publish/topics.ejs
- src/views/publish/update-frequency.ejs
All metadata sections now have a cancel button that returns the user to the tasklist.
> SW-383: Add cancel button to all pages (return to tasklist)

- src/app.ts
Guidance link no longer requires authentication.
> Remove auth requirement from guidance link

- src/routes/consumer.ts
Consumer dataset list route changed from
`/en-GB/published/list` to just `/en-GB/published`
> Simplify the consumer list route

- src/config/app-config.interface.ts
- src/config/envs/ci.ts
- src/config/envs/default.ts
- src/config/envs/local.ts
- src/config/envs/staging.ts
- src/enums/auth-providers.ts
- src/i18n/en.json
- src/routes/auth.ts
- src/views/auth/local.ejs
- src/views/auth/login.ejs
This adds an incredibly basic login form that takes just a username and redirects the user to the backend for the user check. 
**IT IS NOT SECURE and is not intended to be**
This is purely a temporary workaround for testing purposes until we can authenticate WG users via their own EntraID.
To be removed once the testing session is complete.
> Add support for username only login (TEMP)

- src/controllers/publish.ts
- src/dtos/dataset.ts
- src/routes/publish.ts
Only fetch what's required for rendering the metadata page.
Paired with https://github.com/Marvell-Consulting/statswales-backend/pull/109
> Improve metadata performance

- src/controllers/publish.ts
- src/dtos/dimension-metadata.ts
- src/dtos/dimension.ts
- src/dtos/single-language/dimension.ts
- src/routes/publish.ts
- src/services/publisher-api.ts
- src/utils/single-lang-dataset.ts
- src/views/developer/data.ejs
- src/views/publish/dimension-chooser.ejs
- src/views/publish/lookup-table-preview.ejs
- src/views/publish/measure-preview.ejs
- src/views/publish/measure-review.ejs
- src/views/publish/time-chooser.ejs
This PR
* cleans up any remnants of the DimensionInfo -> DimensionMetadata rename
* hides the sample message when total row count < page size
* cleans up the table styling for ref data / lookup previews
* some performance improvements around dimensions
Relies on the updates in https://github.com/Marvell-Consulting/statswales-backend/pull/122
> Various dimension improvements

- src/controllers/publish.ts
- src/i18n/en.json
- src/views/publish/measure-preview.ejs
- src/views/publish/measure-review.ejs
The backend changes meant the measure preview was having issues especially around null value display.  This fixes many of these issues and makes the table more presentable.  It also filters the table to only show the values for the displayed language rather than both languages.
> Fix measure preview/review following backend changes

- src/views/publish/quarter-format.ejs
Wrong ID on the hint means that clicking on the hint results in the wrong radio button being selected as a result.  This PR updates the for and ID values.
> Fix not being able to select `-X` option in Quarter formats

- src/controllers/publish.ts
- src/i18n/en.json
- src/views/publish/preview.ejs
This implements or reimplements the revisit path for the data table on create.  Asks the user what they would like to do as well as clear routes back to the task list.
> Implement revisit on data table for create

- src/routes/auth.ts
- src/services/consumer-api.ts
- tests/mocks/backend.ts
This should prevent a situation where the frontend is displaying auth provider buttons for providers that aren't enabled in the corresponding back end.
> Fetch the enabled auth providers from the backend

- README.md
- docker-compose.yml
- nodemon.json
- package.json
This allows the full StatsWales stack to be run without needing to manually start or configure any external services (backend, db, file storage, etc) as they will all be started automatically inside Docker.
You could even work entirely offline if you have previously pulled the stack by commenting out `pull_policy: always` in `docker-compose.yml`.
This will also be the basis for running full e2e tests in CI.
Try it: 
`npm run localstack`
> SW-543: run the full stack in docker for local dev

- docker-compose.yml
The dockerfile now causes the container to run the migrations before starting up.
We don't want this in localstack env because db autosync is turned on.
> Prevent migrations running in localstack

- src/@types/express-session/index.d.ts
- src/controllers/publish.ts
- src/routes/homepage.ts
- src/utils/user-permissions.ts
Previously noticed an issue where session props used for controlling flow through the publishing journey leaked between different datasets, which resulted in some weird behaviour.
Solution is to ensure these props are namespaced by the dataset id, so different datasets cannot share session values when the user switches between multiple datasets during the same session.
We could potentially do this for flash and error messages as well, but they're automatically cleared on the very next request already, so are less likely to have similar bleed between datasets.
> SW-536: namespace publishing session props using dataset id

- src/views/publish/lookup-table-preview.ejs
- src/views/publish/number-chooser.ejs
- src/views/publish/upload-lookup.ejs
A non-existent partial was introduced by https://github.com/Marvell-Consulting/statswales-frontend/pull/228 causing the page to throw errors. This reverses the breaking changes.
> SW-673: Fix broken partial include

- src/i18n/cy.json
Don't think we need to change the text here, just added the Slack link:
> Update support link to Slack (Welsh)

- src/controllers/publish.ts
- src/i18n/en.json
This adds a check before sending the request to the backend to make sure there is a notes column present during column matching.
> Mandate having a notes code column

- src/middleware/no-cache.ts
- src/routes/admin.ts
- src/routes/developer.ts
- src/routes/publish.ts
Users keep complaining about seeing stale statuses in the tasklist, so just force their browser to always refetch.
> SW-675: Set cache-control no-cache header for pub/dev routes

- src/controllers/publish.ts
Previously we set the initial dimension name to the fact column name, now it is set to an empty string. This should be used to determine revisit status
> Fix revisit logic for dimension

- src/services/consumer-api.ts
Updates the consumer api to use versioned routes.
Related backend changes: https://github.com/Marvell-Consulting/statswales-backend/pull/280
> SW-388: use versioned consumer API

- src/views/components/Filters.tsx
Counter wasn't including the node itself in the count if there were child nodes.
> filter with children should still count itself

- src/controllers/publish.ts
There was a bug where refreshing the task decision page after it was already closed left us with broken translations due to the task having the status of withdrawn.
This is not a valid screen so just redirect the user back to the overview page.
> if the task was already closed, just redirect back to overview

- Dockerfile
The docs dir got missed when we hardened the frontend image.
It's needed for the guidance.
> Fix guidance is broken on frontend

- src/public/css/app.css
- src/public/scss/_wg.scss
- src/views/components/Tabs.tsx
- src/views/consumer/view.jsx
* Updated focus link styles to include yellow outline
* Fixed bug with tabs where listeners were firing twice, meaning second tab could not be selected with keyboard
> Bugfix - SW-816 - tabs and links focus fixes

- src/views/publish/related-links.jsx
The reports links were rendering as relative paths rather than full URLs resulting in the links failing to work when they're clicked on.  Minor fix to a minor issue.
> Fix broken link on reports

- src/controllers/publish.ts
- src/dtos/update-frequency.ts
- src/enums/duration-unit.ts
- src/enums/update-type.ts
- src/i18n/cy.json
- src/i18n/en.json
- src/interfaces/preview-metadata.ts
- src/utils/dataset-preview.ts
- src/utils/next-update-at.ts
- src/validators/index.ts
- src/views/components/dataset/KeyInfo.jsx
- src/views/publish/tasklist.jsx
- src/views/publish/update-frequency.jsx
- tests-e2e/required/happy-path.spec.ts
Previously we just allowed the user to specify an interval for the next update.
This updates the UI to provide radio buttons to determine the type of update, and a date input to specify the expected update date.
> SW-739: update frequency is now captured as a date input

- src/publisher/controllers/publish.ts
- src/publisher/validators/index.ts
- src/publisher/views/publish/preview.jsx
- src/publisher/views/publish/update-type.jsx
- src/publisher/views/publish/upload.jsx
- src/shared/dtos/data-table.ts
- src/shared/dtos/update-frequency.ts
- src/shared/enums/data-table-action.ts
- src/shared/enums/next-update-type.ts
- src/shared/validators/index.ts
- src/shared/views/components/dataset/KeyInfo.jsx
Make it clear what type of update is in progress when rendering the update journey.
> SW-898: show data update type as subheading on upload & upload preview pages

- src/consumer/views/view.jsx
- src/shared/dtos/dataset.ts
- src/shared/dtos/publisher-dto.ts
- src/shared/dtos/single-language/dataset.ts
- src/shared/interfaces/preview-metadata.ts
- src/shared/utils/dataset-preview.ts
- src/shared/views/components/dataset/Publisher.jsx
Displays the publisher contact info on the about page of the dataset.
> SW-561: Add publisher contact info to about dataset tab

- src/publisher/views/publish/overview.jsx
- src/shared/i18n/en.json
When a user is reviewing a dataset, then it makes sense to open it in a new tab so that they can still see the overview / approval screen.
> SW-942: open dataset preview in a new tab from overview

- src/consumer/services/consumer-api.ts
- src/publisher/services/publisher-api.ts
- tests/publisher-api.test.ts
We were not logging the original fetch error message if it rejected and threw an error
> Better fetch errors

- src/publisher/views/publish/empty-fact.jsx
At some point this got extracted to a separate component and the prop path was not updated.
Also fixed an errant colon that was appearing in the rendered page.
> SW-926: incomplete facts error page was failing to render because of broken object path

- src/shared/utils/single-lang-dataset.ts
If we do not have a translated title yet, then display the original title along with "Not yet translated" in the appropriate language.
> SW-817: show alternate title + [Not yet translated] if not available in current language

- src/publisher/views/publish/providers.jsx
- src/shared/i18n/cy.json
- src/shared/i18n/en.json
Previously we updated the support email link for adding a provider.
Use the same mailto: support address for "request a data source be added"
> SW-933: add same support link for request a data source

- src/consumer/app.ts
- src/shared/middleware/history.ts
Consumer side was missing history due to no session middleware being active.
> Re-add session middleware to consumer side

- src/shared/middleware/history.ts
- src/shared/routes/cookies.ts
Feedback from team review - 
If user "accepts all" from the cookie banner without visiting the cookie settings page, automatically return them to the original url after saving.
> SW-696: accept all cookies improvement

- src/publisher/controllers/publish.ts
- src/publisher/views/publish/dimension-match-failure.jsx
- src/shared/i18n/en.json
Previously we were just showing a not very helpful "errors.csv.unknown" untranslated message when a lookup table contained empty rows.
We now trigger the `dimension-match-failure` error page and I've added an additional item to the "you should check" list.
> SW-853: display error page when lookup table contains empty rows

- src/consumer/controllers/consumer.ts
- src/consumer/services/consumer-api.ts
- src/publisher/controllers/publish.ts
- src/shared/utils/parse-filters.ts
- src/shared/views/components/Filters.tsx
This fixes an issue with cube preview / consumer view when dimension values contain non-alphanumeric characters such as `[`, `]`, etc.
These values need escaping/encoding as they're used in the checkbox input name and can cause issues with parsing the form data correctly.
There is also a slight performance improvement by fetching the data and available filters in parallel instead of sequentially.
> SW-956: Escape dimension values in filters

- src/consumer/views/view.jsx
- src/publisher/controllers/developer.ts
- src/publisher/services/publisher-api.ts
- src/publisher/views/developer/list.jsx
- src/shared/i18n/en.json
On some environments the full list of datasets is going to be long, and it would be really handy to be able to just find a dataset by title when trying to debug.
Search might also be useful to publishers but we can prototype it on the dev list first.
> Add search box to dev dataset list

- src/shared/middleware/translation.ts
- src/shared/routes/cookies.ts
I was seeing an issue where on first return from login, the cookie banner displayed despite the cookiePref cookie being set to hide the banner.
On further inspection, this was because Chrome filters out `SameSite=Strict` cookies from requests made from other domains (such as a redirect from the backend after auth).
The banner would disappear again once you started navigating the frontend, as Chrome sent the cookie with those requests.
The solution is to use "Lax" rather than "Strict" for SameSite as it allows cookies to be sent on GET requests from other domains whilst retaining protection against POST requests as a CSRF measure.
As an added bonus, this was also preventing the language cookie from being read after returning from login, and the same fix on that allows the language …
> Don't show cookie banner on return from login

- docs/static-pages/shorthand.cy.md
- docs/static-pages/shorthand.en.md
- src/consumer/controllers/consumer.ts
- src/consumer/views/view.jsx
- src/publisher/controllers/publish.ts
- src/shared/dtos/view-dto.ts
- src/shared/i18n/en.json
- src/shared/routes/static-pages.ts
Adds a legend at the top of the cube preview/consumer view that displays the note codes and their definitions, along with a link to a table with the full set of codes.
> SW-482: Note code shorthand docs

- src/publisher/controllers/publish.ts
Fixes date validation to make sure the number of days are present in the month.  `isDate(str)` does not handle leap years accurately so returns false for 2024-02-29 which is a vlidate date.  So instead we check the day entered against the number of days in the month.
> SW-915 Fix date validatation for invalid dates

- package-lock.json
- src/publisher/controllers/admin.ts
- src/publisher/routes/admin.ts
- src/publisher/services/publisher-api.ts
- src/publisher/views/admin/user-group-status.jsx
- src/publisher/views/admin/user-group-view.jsx
- src/shared/dtos/single-language/user-group.ts
- src/shared/dtos/user/user-group.ts
- src/shared/enums/user-group-action.ts
- src/shared/enums/user-group-status.ts
- src/shared/i18n/en.json
- src/shared/utils/single-lang-user-group.ts
Adds the UI for deactivating user groups. Only groups with no assigned datasets can be deactivated. All users will be removed from the group, and will not be automatically re-added on reactivation.
> SW-589: user group deactivate / reactivate

- src/shared/utils/dataset-metadata.ts
The metadata property names were already calling the translation function, but no locale was being passed in so it always fell back to English.
> SW-1039: fix translations in meta csv download

- src/consumer/views/components/Layout.tsx
- src/publisher/views/components/Layout.tsx
Forgot that the publisher hostnames start with `publisher.` so the first subdomain is always the same regardless of dev /preview.
Just set the correct value instead of trying to split it out.
> fix issue with env badges showing "publisher"
