src/controllers/api.ts, src/resources/locales/en-GB.json, test/app.test.ts
Update the API endpoints to match the changes to the Backend. Additionally update the App to specify Beta in the main title.
=> Update API Endpoints

src/app.ts, src/resources/locales/en-GB.json, src/views/data.ejs, src/views/index.ejs, src/views/list.ejs, src/views/partials/top.ejs, src/views/publish/start.ejs, src/views/publish/upload.ejs, test/app.test.ts
This PR implements the Publishing journey start page.  It relocates the upload page to form part of this user journey.  Additionally changes were made to move the 'Beta banner' to the top partial.
Proposed screenshot:
Delivered screenshot:
=> 192 Implement Publishing Intro Page

package-lock.json, package.json, src/app.ts, src/config/auth_config.ts, src/config/authenticate.ts, src/config/i18next.ts, src/controllers/api.ts, src/resources/locales/cy-GB.json, src/route/healthcheck.ts, src/route/publish.ts, src/route/view.ts, src/views/login.ejs, src/views/partials/bottom.ejs, src/views/publish/title.ejs, test/app.test.ts
This adds authentication against Googles OAuth provider.  With this implemented it should be straight forward to add other authentication providers to our App such as ActiveDirectory, OneLogin For Governement or social logins such as FaceBook.
We need to properly implement user storage and user management in to the system along with RBAC.
=> Implement Authentication using Google OAuth

package-lock.json, package.json, src/@types/express-session/index.d.ts, src/app.ts, src/middleware/session.ts, src/routes/publish.ts, test/app.test.ts
Implements redis for session storage.  Pipeline needs to be updated with a new `REDIS_URL` and `REDIS_ACCESS_KEY` variables to run.
=> Implement Redis Session Storage

src/views/index.ejs, src/views/view/list.ejs
Fixes the broken link on the home page.  Fixes a small bug where you might not have a file list array before you look at its length.  Fixes the error this creates.
=> Minor broken link in the view and an issue when there are no datasets

azure-pipelines.yml, src/config/envs/production.ts, src/config/envs/staging.ts, src/middleware/session.ts
Add the new env vars to the pipeline, set session store to Redis for staging & prod.
=> Add new env vars to deploy

src/views/view/data.ejs
We ended up with rev.rev.created_at.
=> Fix issue in view

src/app.ts, src/config/app-config.interface.ts, src/config/envs/default.ts, src/enums/locale.ts, src/exceptions/not-found.exception.ts, src/middleware/ensure-authenticated.ts, src/middleware/language-switcher.ts, src/middleware/translation.ts, src/middleware/translations/cy.json, src/middleware/translations/en.json, src/routes/healthcheck.ts, src/routes/homepage.ts, src/routes/view.ts, src/views/partials/footer.ejs, src/views/partials/header.ejs, src/views/publish/start.ejs, src/views/view/data.ejs, test/app.test.ts, test/publish.test.ts
This fixes the following issues around language switching:
FIX - We now cache the selected language in a "lang" cookie so if a URL is hit without a locale in the path, we use the cookie lang if available before defaulting to browser lang.
FIX - The language switching now uses a query param and will work on any page.
FIX - The language switching link is always in the alternate language
=> Various language bug fixes

src/middleware/translations/cy.json, src/middleware/translations/en.json, src/routes/publish.ts, src/views/partials/header.ejs, src/views/publish/preview.ejs, test/publish.test.ts
This updates the welsh translation to match the english.  Improved 2 strings on the preview and removed a hardcoded string a replaced it with a translation call.
=> Updated translation file with fixes for broken/missing strings

src/controllers/publish.ts, src/middleware/translations/en.json, src/routes/publish.ts, src/validators/index.ts, src/views/publish/summary.ejs, src/views/publish/title.ejs
Adds a form for capturing dataset summary metadata.
=> SW-128: Metadata - Dataset Summary

src/controllers/publish.ts, src/dtos/dataset-info.ts, src/middleware/translations/en.json, src/routes/publish.ts, src/validators/index.ts, src/views/publish/collection.ejs, src/views/publish/tasklist.ejs
Adds a form for capturing data collection metadata.
=> SW-129: Metadata - Data Collection

src/controllers/publish.ts, src/dtos/dataset-info.ts, src/enums/designation.ts, src/middleware/translations/en.json, src/routes/publish.ts, src/validators/index.ts, src/views/publish/designation.ejs
Adds a form for collecting designation metadata.
=> SW-137: Metadata Designation

src/controllers/publish.ts, src/dtos/dataset-info.ts, src/dtos/update-frequency.ts, src/enums/duration-unit.ts, src/middleware/translations/en.json, src/routes/publish.ts, src/validators/index.ts, src/views/publish/update-frequency.ejs
Form for collecting metadata about how often the dataset is updated.
=> SW-136: Metadata Update Frequency

package-lock.json, package.json, src/controllers/publish.ts, src/dtos/dataset-info.ts, src/dtos/related-link.ts, src/middleware/translations/en.json, src/routes/publish.ts, src/validators/index.ts, src/views/publish/related-links.ejs
Adds a form for managing related links.
=> SW-134: Metadata Related Reports

src/middleware/translations/en.json, src/views/publish/related-links.ejs
Implemented some fixes requested by the design team.
=> Fix: Use single col for related link and prevent actions wrapping

src/controllers/publish.ts, src/dtos/view-error.ts, src/middleware/translations/en.json, src/public/css/wales-overrides.css, src/views/partials/header.ejs, src/views/publish/providers.ejs
- Fix: autocomplete now has correct font
- Fix: autocomplete now displays drop-down arrow
- Fix: forms now show validation error if submitted without a selection
- Improvement: removed redundant "change" action
- Improvement: select source for provider now displays just a provider name and not a table
Before: 
After:
=> SW-326: Various fixes for Metadata - Data Sources

src/controllers/publish.ts, src/dtos/dataset-topic.ts, src/dtos/dataset.ts, src/dtos/single-language/dataset.ts, src/dtos/topic.ts, src/middleware/translations/en.json, src/routes/publish.ts, src/services/stats-wales-api.ts, src/utils/nested-topics.ts, src/validators/index.ts, src/views/publish/providers.ejs, src/views/publish/topics.ejs
Adds a form for managing dataset topics.
=> SW-293: Metadata Relevant Topics

src/@types/express-session/index.d.ts, src/controllers/publish.ts, src/dtos/dimension-patch-dto.ts, src/dtos/dimension-state.ts, src/dtos/task-list-state.ts, src/dtos/view-dto.ts, src/enums/year-type.ts, src/exceptions/api.exception.ts, src/i18n/en.json, src/middleware/services.ts, src/routes/publish.ts, src/services/stats-wales-api.ts, src/validators/index.ts, src/views/publish/dimension-chooser.ejs, src/views/publish/dimension-name.ejs, src/views/publish/month-format.ejs, src/views/publish/period-match-failure.ejs, src/views/publish/period-type.ejs, src/views/publish/point-in-time-chooser.ejs, src/views/publish/quarter-format.ejs, src/views/publish/tasklist.ejs, src/views/publish/time-chooser.ejs, src/views/publish/year-format.ejs, src/views/publish/year-type.ejs, test/mocks/fixtures.ts, test/publish.test.ts
This is our first iteration on a dimension matching journey in beta.  It allows matching statistically encoded dates to be matched against real dates based on the formats the user chooses.
The is the first stage of the dimension creation process.  Next up is lookup tables and reference data.
=> This implements date period and point in time matching

src/controllers/publish.ts
=> fix typo in error key

src/views/publish/point-in-time-chooser.ejs
Fixes an issue where the wrong values are encoded in the frontend.  Its trying to set specific point in time formats as all caps when they shouldn't be.
=> Fixes issues where the wrong values are encoded in frontend

src/controllers/publish.ts, src/enums/dimension-type.ts, src/i18n/en.json, src/routes/publish.ts, src/services/stats-wales-api.ts, src/views/publish/dimension-chooser.ejs, src/views/publish/lookup-table-preview.ejs, src/views/publish/upload.ejs
Implements the lookup table journey.  Doesn't support column identification but this isn't part of the MVP.
=> Implement lookup table journey

package-lock.json, package.json, src/controllers/publish.ts, src/dtos/translations.ts, src/enums/task-status.ts, src/i18n/en.json, src/routes/publish.ts, src/services/stats-wales-api.ts, src/utils/add-edit-links.ts, src/utils/status-to-colour.ts, src/views/publish/start.ejs, src/views/publish/tasklist.ejs, src/views/publish/translations/export.ejs, src/views/publish/translations/import.ejs
Adds a page for exporting translations.
=> SW-159: Translation export & import

src/controllers/publish.ts, src/i18n/en.json, src/views/publish/dimension-chooser.ejs, src/views/publish/dimension-match-failure.ejs, src/views/publish/measure-match-failure.ejs
Implements reference data in frontend.  Fixes a few bugs and content errors from the previous PR.
=> Implement Reference data in the frontend

src/i18n/cy.json, src/i18n/en.json, src/routes/auth.ts, src/views/auth/login.ejs, tests-e2e/login.spec.ts, tests/auth.test.ts
This replaces OneLogin authentication with EntraID
=> SW-286: Replace OneLogin with EntraID (Microsoft Azure AD)

src/i18n/en.json, src/views/publish/measure-preview.ejs
Fixed some issues from the design review.
=> SW-52: Fix measure upload page content

src/controllers/publish.ts, src/dtos/task-list-state.ts, src/i18n/en.json, src/routes/publish.ts, src/services/stats-wales-api.ts, src/utils/dataset-status.ts, src/utils/latest.ts, src/views/homepage.ejs, src/views/publish/overview.ejs, src/views/publish/tasklist.ejs, tests/mocks/fixtures.ts
Adds a button at the bottom of a completed tasklist to submit the dataset for publication.
Once submitted, the user is taken to the dataset overview page and they can see the status and publish date.
=> SW-337: Submit dataset for publication

src/controllers/publish.ts, src/i18n/en.json, src/routes/publish.ts, src/services/stats-wales-api.ts, src/views/publish/overview.ejs
This adds a new action that will revert the scheduled dataset publication back to the "Incomplete" or draft status.
=> SW-338: Allow user to withdraw publication and revert to tasklist

src/i18n/en.json, src/views/publish/overview.ejs
=> Display time before date

src/i18n/en.json
=> add missing translation

src/controllers/publish.ts, src/i18n/en.json, src/views/publish/overview.ejs, src/views/publish/tasklist.ejs
=> SW-441: add status badges to tasklist

docs/cookies/cy/cookie-statement.md, src/i18n/cy.json
This is the first step translations for the Start of February with a veiw to doing a longer more context aware translation before the end of the month.
=> First step translations for February

src/routes/guidance.ts, src/services/marked.ts
=> SW-411: Apply link styling to guidance ToC

src/controllers/consumer.ts, src/middleware/fetch-dataset.ts, src/utils/dataset-preview.ts, src/utils/dataset-status.ts, src/utils/revision.ts
"Most recent update" was showing the wrong date.
=> SW-463: fix most recent update & revision sort order on dataset views

package.json, src/controllers/publish.ts, src/dtos/view-error.ts, src/i18n/en.json, src/views/publish/dimension-chooser.ejs, src/views/publish/measure-preview.ejs, src/views/publish/month-format.ejs, src/views/publish/period-type.ejs, src/views/publish/quarter-format.ejs, src/views/publish/year-format.ejs, src/views/publish/year-type.ejs
This fixes issues where the user fails to select an option duing the create dataset journey.  Adds error messages from when the user fails to select an option.  Also disables Reference data which isn't geography while we wait for a reference data decision to be made.
=> Fixes the service appearing to hang when use doesn't select an option

src/controllers/publish.ts, src/i18n/en.json, src/routes/publish.ts, src/views/publish/dimension-chooser.ejs, src/views/publish/dimension-name.ejs, src/views/publish/dimension-revisit.ejs, src/views/publish/time-revisit.ejs, src/views/publish/upload.ejs
Adds new pages for revisiting a dimension, allows aspects like the name and format and lookup tables of dimensions to be changed.
=> Fixes the dimension revisit and dimension name issues

.github/workflows/deploy-frontend.yml
Ensure that deploy only runs against main branch
=> only run against main when docker finishes

package-lock.json, package.json, src/controllers/consumer.ts, src/controllers/publish.ts, src/enums/file-format.ts, src/services/consumer-api.ts, src/utils/download-headers.ts, src/views/partials/dataset/download.ejs, src/views/partials/header.ejs, src/views/publish/cube-preview.ejs
As a small added bonus switches from using the id of the dataset/revision to using a slugified version of the title which is easier to find and understand.
=> Fixes downloads on conumer and publisher

src/dtos/single-language/user-group.ts, src/dtos/user/user-group.ts, src/dtos/user/user-with-roles-dto.ts, src/i18n/en.json, src/views/admin/user-group-view.ejs
Updates the group view page to include a list of assigned users.
=> SW-583: View users in a group

src/controllers/admin.ts, src/i18n/en.json, src/public/css/app.css, src/public/scss/_wg.scss, src/views/admin/user-group-list.ejs, src/views/admin/user-group-view.ejs, src/views/admin/user-roles.ejs, src/views/admin/user-view.ejs, src/views/partials/flash-messages.ejs
Various fixes raised in the team review of the user group create/update journeys.
=> SW-622: improvements for group management

src/@types/express-session/index.d.ts, src/controllers/admin.ts, src/i18n/en.json, src/interfaces/flash-message.ts, src/validators/admin.ts, src/views/admin/user-view.ejs, src/views/partials/flash-messages.ejs
Improvements requested during design review of the user management journeys.
=> SW-644: improvements to user create/update journey

src/controllers/admin.ts, src/enums/user-action.ts, src/i18n/en.json, src/routes/admin.ts, src/services/publisher-api.ts, src/views/admin/user-status.ejs
Adds UI for deactivating / reactivating user accounts.
=> SW-587: deactivate/reactivate user

src/utils/add-edit-links.ts
* Updated change link for dimension to link to /change-name
* Updated change link for links to link to ?edit={key}
=> SW-635 - change links for translations should link to change pages

src/controllers/admin.ts, src/views/admin/user-group-list.ejs, src/views/admin/user-list.ejs
Missed this off the list pages.
=> Pagination UI for user/group lists

src/app.ts, src/controllers/admin.ts, src/dtos/dataset-list-item.ts, src/i18n/cy.json, src/i18n/en.json, src/middleware/ensure-admin.ts, src/middleware/ensure-developer.ts, src/middleware/fetch-dataset.ts, src/routes/admin.ts, src/routes/developer.ts, src/routes/error-handler.ts, src/views/errors/forbidden.ejs, src/views/homepage.ejs
User's will now get a 403 Forbidden page if they try and access datasets / revisions / etc owned by groups they are not a member of.
=> SW-588: Limit dataset access to users in the assigned group

src/controllers/publish.ts, src/i18n/en.json, src/routes/publish.ts, src/services/publisher-api.ts, src/views/publish/delete-draft.ejs, src/views/publish/tasklist.ejs
Updates the delete draft UI to include updates as well.
=> Delete a draft update

src/views/consumer/view.ejs
=> Fix sticky table headings

src/i18n/en.json, src/middleware/services.ts
* Updated dateFormat helper to use TZDate and take BST into account
* Updated helper text for publish date
=> Bugfix - SW-643 - playback dates in UK tz

src/services/publisher-api.ts
This is needs to be merged along with https://github.com/Marvell-Consulting/statswales-backend/pull/233
=> Move dataset/xyz routes to dataset?hydrate=xyz

src/controllers/publish.ts, src/dtos/dataset.ts
Needs https://github.com/Marvell-Consulting/statswales-backend/pull/236
=> use endRev for preview instead of draft

src/views/consumer/view.ejs
Typo in the if statement for the developer tab
=> Fix developer view

src/services/marked.ts
* Updated guidance table renderer to wrap in container
=> Bugfix - guidance tables

src/views/admin/user-group-org.jsx, src/views/components/RadioGroup.jsx, src/views/components/T.jsx, src/views/components/layouts/Publisher.jsx, src/views/consumer/view.jsx, src/views/context/Locals.jsx, src/views/publish/date-chooser.jsx, src/views/publish/designation.jsx, src/views/publish/dimension-chooser.jsx, src/views/publish/month-format.jsx, src/views/publish/move-group.jsx, src/views/publish/number-chooser.jsx, src/views/publish/period-type.jsx, src/views/publish/preview.jsx, src/views/publish/providers.jsx, src/views/publish/quality.jsx, src/views/publish/quarter-format.jsx, src/views/publish/related-links.jsx, src/views/publish/select-group.jsx, src/views/publish/specific-date-chooser.jsx, src/views/publish/task-decision.jsx, src/views/publish/update-frequency.jsx, src/views/publish/update-type.jsx, src/views/publish/year-format.jsx, src/views/publish/year-type.jsx, tests-e2e/required/happy-path.spec.ts
* Added RadioGroup component
* Replaced instances of radios with radio group
* Added locals context
* Added T component which translates including raw html
=> Chore - radio group and T

src/config/app-config.interface.ts, src/config/envs/ci.ts, src/config/envs/default.ts, src/controllers/publish.ts, src/middleware/services.ts, src/views/components/T.jsx, src/views/components/layouts/Publisher.jsx
* Updated config supportEmail to accept en and cy strings
* Updated providers controller to provide email link to request data provider
* Updated footer link to use correct language support link
=> Bugfix - SW-742 - missing request data provider link

src/i18n/en.json, src/views/publish/overview.jsx
Add a "System" user for simulated system events.
=> Improved history log

src/i18n/cy.json, src/i18n/en.json, src/views/components/DimensionPreviewTable.tsx, src/views/components/TranslationsPreviewTable.tsx
* Updated malformatted template strings
* Updated key -> value, key is a reserved prop name in react
=> Bugfix - template translation errors

src/views/publish/overview.jsx
Withdrawing update label wasn't showing for the pending approval status
=> Fix withdraw update label

src/i18n/cy.json, tests-e2e/publish/5-sources.spec.ts, tests-e2e/publish/meta-designation.spec.ts, tests-e2e/publish/meta-topics.spec.ts
We've done a new string translation of English to Welsh.  This PR updates the Welsh translation to bring it inline with the English.
=> Update welsh translations

src/controllers/consumer.ts, src/services/consumer-api.ts, src/views/consumer/view.jsx, tests-e2e/required/happy-path.spec.ts
Adds the option for downloads to be filtered on the frontend.
=> Implement filtered downloads on the frontend

.github/workflows/node-test.yml, Dockerfile, docker-compose.yml
This updates the frontend dockerfile to use a multi-stage build that uses node alpine for the final stage and only installs prod dependencies.
=> SW-360: reduce attack surface of frontend image

package-lock.json, package.json, src/app.ts, src/middleware/strict-transport.ts
Add Strict-Transport-Security header as recommended by IT Healthcheck.
=> Add Strict-Transport-Security header

src/controllers/publish.ts, src/i18n/cy.json, src/i18n/en.json, src/views/components/T.tsx, src/views/publish/sources.jsx
Also improves the validation errors (SW-368).
=> SW-874: Enforce 1 measure column in source selection

src/controllers/publish.ts, src/dtos/dimension-patch-dto.ts, src/enums/year-type.ts, src/i18n/en.json, src/views/publish/year-type.jsx
Adds the neccessary changes to add support for rolling year.
=> Add support for rolling years

src/public/scss/_wg.scss
* Updated th a to add pseudo clickable element
* Added focus styles
=> Accessibility - SW-910 - make whole TH clickable

src/consumer/views/components/Layout.tsx, src/consumer/views/view.jsx, src/publisher/views/components/Layout.tsx, src/shared/i18n/en.json, src/shared/views/components/CheckboxGroup.tsx, src/shared/views/components/Filters.tsx, src/shared/views/components/Select.tsx
* Updated consumer view to address ARC issues
* Moved select all/none to below parent
* Updated behaviour to select all children, including descendents
* Auto expand/collapse on select all/none
* Updated labels for screenreaders
=> Accessibility changes SW-911

src/shared/i18n/en.json
=> SW-971: wording improvement

src/shared/i18n/cy.json, src/shared/i18n/en.json
Missed the page title from the translation files
=> SW-766: add missing title

src/publisher/controllers/publish.ts
=> SW-1001: add specific error message when lookup has dupes

src/publisher/controllers/admin.ts, src/publisher/services/publisher-api.ts, src/publisher/views/admin/user-list.jsx, src/publisher/views/developer/list.jsx, src/publisher/views/homepage.jsx, src/shared/i18n/en.json, src/shared/public/scss/app.scss
Allows an admin user to search the user list by name or email address.
=> SW-692: User list - search by name or email

src/publisher/controllers/developer.ts
Small fixes to the developer downloads to make datatables and measures work again.
=> Fix downloads from developer page

src/publisher/middleware/ensure-authenticated.ts, src/publisher/routes/auth.ts, tests/auth.test.ts
Also removes the google auth route on the frontend
=> Better auth logging

src/consumer/views/topic-list.jsx, src/shared/i18n/en.json
=> add archived status badge in topic list when appropriate

src/publisher/views/publish/overview/overview.jsx, src/shared/i18n/en.json
=> SW-945: add user group name to dataset overview

src/consumer/middleware/services.ts, src/consumer/views/components/Layout.tsx, src/publisher/middleware/services.ts, src/publisher/views/components/Layout.tsx
Add Google Analytics tracking code to both the consumer and publisher frontends in staging and prod.
=> SW-336: Google Analytics

src/shared/middleware/translation.ts
Switch default language to Welsh when on the Welsh domain (stats.llyw.cymru).
Switch default language to English when on the English domain (stats.gov.wales).
Language precedence is 'querystring', 'path', 'cookie', 'domain', 'header'.
=> SW-1035: domain based language detection

src/shared/middleware/translation.ts
Lang cookie is not being set on Welsh language domain... try removing the forced cookie domain option and let the middleware determine the cookie domain itself.
=> let i18next decide the cookie domain
